repos:
-   repo: local
    hooks:
    -   id: black
        name: Running Black
        entry: poetry run black skim/ test/
        language: system
        types: [python]
    -   id: mypy
        name: Running MyPy
        entry: poetry run mypy
        language: system
        files: 'skim/(.*)$'
    -   id: pytest
        name: Running Pytest
        entry: poetry run pytest
        language: system
        files: 'test/(.*)\.py$'
        always_run: true
        types: [python]
